version: '3.4'
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    networks:
    - ciNet
    environment:
    - VIRTUAL_HOST=${SONAR_URL}
    - VIRTUAL_PORT=9000
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
    - ./data/sonarqube/conf:/opt/sonarqube/conf
    - ./data/sonarqube/data:/opt/sonarqube/data
    - ./data/sonarqube/extensions:/opt/sonarqube/extensions
    - ./data/sonarqube/lib/bundled-plugins-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
    - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    networks:
    - ciNet
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    volumes:
    - ./data/postgresql:/var/lib/postgresql
    - ./data/postgresql/data:/var/lib/postgresql/data

  jenkins:
    build:
      dockerfile: Dockerfile
      context: ./jenkins
    privileged: true
    user: root
    container_name: jenkins
    networks:
    - ciNet
    environment:
    - VIRTUAL_HOST=${JENKINS_URL}
    - VIRTUAL_PORT=8080
    volumes:
    - ./data/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - sonarqube

  nginx:
    image: jwilder/nginx-proxy
    ports:
    - 80:80
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
    - ciNet
    - ciExternalNet

networks:
  ciNet:
    driver: bridge
  ciExternalNet:
    external:
      name: ciNetwork
